// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHY1U5-rG1uJgRCtB5vUzTWbhWt-rSYvo',
    appId: '1:694481745750:android:e9453197462329868308f7',
    messagingSenderId: '694481745750',
    projectId: 'my-flutter-lab12-1ca7f',
    storageBucket: 'my-flutter-lab12-1ca7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGZNMCYsjkuuiu1a12lecEpqDZgbmmJ5Y',
    appId: '1:694481745750:ios:e5c9f062fe2853968308f7',
    messagingSenderId: '694481745750',
    projectId: 'my-flutter-lab12-1ca7f',
    storageBucket: 'my-flutter-lab12-1ca7f.firebasestorage.app',
    iosBundleId: 'com.example.swiftmartApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUdNTgnEKE8vqxB4P3Gv711epxvc_nxks',
    appId: '1:694481745750:web:df0953691d89fa978308f7',
    messagingSenderId: '694481745750',
    projectId: 'my-flutter-lab12-1ca7f',
    authDomain: 'my-flutter-lab12-1ca7f.firebaseapp.com',
    storageBucket: 'my-flutter-lab12-1ca7f.firebasestorage.app',
    measurementId: 'G-YB0V3089HZ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUdNTgnEKE8vqxB4P3Gv711epxvc_nxks',
    appId: '1:694481745750:web:ede3b2a890c6b9768308f7',
    messagingSenderId: '694481745750',
    projectId: 'my-flutter-lab12-1ca7f',
    authDomain: 'my-flutter-lab12-1ca7f.firebaseapp.com',
    storageBucket: 'my-flutter-lab12-1ca7f.firebasestorage.app',
    measurementId: 'G-HGL305DCWL',
  );
}
